"""added image column for menu items

Revision ID: 65a67a8d9ad4
Revises: e8e08d172866
Create Date: 2023-05-09 20:56:44.690913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a67a8d9ad4'
down_revision = 'e8e08d172866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
